plugins {
    id 'java'
}

java {
    sourceCompatibility=11
}

compileJava.options.encoding="UTF-8"
compileTestJava.options.encoding="UTF-8"

group = 'ru.netology.javaQA'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation('com.codeborne.selenide:6.19.1')
    testCompileOnly('org.projectlombok:lombok:1.18.36')
    testAnnotationProcessor('org.projectlombok:lombok:1.18.36')
    testImplementation('org.slf4j:slf4j-simple:2.0.3')
}

test {
    useJUnitPlatform()
    systemProperty 'selenide.headless', System.getProperty('selenide.headless')
    systemProperty 'chromeoptions.prefs', System.getProperty('chromeoptions.prefs', "profile.password_manager_leak_detection=false")
}